In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# 1. Extract year

In [11]:
date['date_year'] = date['date'].dt.year

date.sample(5)

,date,product_id,city_id,orders,date_month_no,date_month_name,date_year
473,2019-05-15,1896,25,4,5,May,2019
25,2018-09-14,4487,14,1,9,September,2018
459,2019-05-02,3803,21,2,5,May,2019
185,2019-11-29,4294,14,4,11,November,2019
553,2019-05-29,2381,18,4,5,May,2019

# 2. Extract Month

In [9]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_month_no
0 2019-12-10        5628       25       3             12
1 2018-08-15        3646       14     157              8
2 2018-10-23        1859       25       1             10
3 2019-08-17        7292       25       1              8
4 2019-01-06        4344       25       3              1

In [10]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  date_month_no date_month_name
0 2019-12-10        5628       25       3             12        December
1 2018-08-15        3646       14     157              8          August
2 2018-10-23        1859       25       1             10         October
3 2019-08-17        7292       25       1              8          August
4 2019-01-06        4344       25       3              1         January

# 3. Extract Days

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_month_no,date_month_name,date_year,date_day
0,2019-12-10,5628,25,3,12,December,2019,10
1,2018-08-15,3646,14,157,8,August,2018,15
2,2018-10-23,1859,25,1,10,October,2018,23
3,2019-08-17,7292,25,1,8,August,2019,17
4,2019-01-06,4344,25,3,1,January,2019,6

In [13]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_month_no,date_month_name,date_year,date_day,date_dow
0,2019-12-10,5628,25,3,12,December,2019,10,1
1,2018-08-15,3646,14,157,8,August,2018,15,2
2,2018-10-23,1859,25,1,10,October,2018,23,1
3,2019-08-17,7292,25,1,8,August,2019,17,5
4,2019-01-06,4344,25,3,1,January,2019,6,6

In [14]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_month_no,date_month_name,date_year,date_day,date_dow,date_dow_name
0,2019-12-10,12,December,2019,10,1,Tuesday
1,2018-08-15,8,August,2018,15,2,Wednesday
2,2018-10-23,10,October,2018,23,1,Tuesday
3,2019-08-17,8,August,2019,17,5,Saturday
4,2019-01-06,1,January,2019,6,6,Sunday

In [15]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_month_no,date_month_name,date_year,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,12,December,2019,10,1,Tuesday,0
1,2018-08-15,8,August,2018,15,2,Wednesday,0
2,2018-10-23,10,October,2018,23,1,Tuesday,0
3,2019-08-17,8,August,2019,17,5,Saturday,1
4,2019-01-06,1,January,2019,6,6,Sunday,1

# Extract week of the year

In [17]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_month_no,date_month_name,date_year,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,12,December,2019,10,1,Tuesday,0,50
1,2018-08-15,8,August,2018,15,2,Wednesday,0,33
2,2018-10-23,10,October,2018,23,1,Tuesday,0,43
3,2019-08-17,8,August,2019,17,5,Saturday,1,33
4,2019-01-06,1,January,2019,6,6,Sunday,1,1

# Extract Quarter

In [18]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_month_no,date_month_name,date_year,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,12,December,2019,10,1,Tuesday,0,50,4
1,2018-08-15,8,August,2018,15,2,Wednesday,0,33,3
2,2018-10-23,10,October,2018,23,1,Tuesday,0,43,4
3,2019-08-17,8,August,2019,17,5,Saturday,1,33,3
4,2019-01-06,1,January,2019,6,6,Sunday,1,1,1

# Extract Semester

In [19]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_month_no,date_month_name,date_year,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,12,December,2019,10,1,Tuesday,0,50,4,2
1,2018-08-15,8,August,2018,15,2,Wednesday,0,33,3,2
2,2018-10-23,10,October,2018,23,1,Tuesday,0,43,4,2
3,2019-08-17,8,August,2019,17,5,Saturday,1,33,3,2
4,2019-01-06,1,January,2019,6,6,Sunday,1,1,1,1

# Extract Time elapsed between dates

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 9, 1, 19, 41, 646794)

In [21]:
today - date['date']

0     2403 days 01:19:41.646794
1     2885 days 01:19:41.646794
2     2816 days 01:19:41.646794
3     2518 days 01:19:41.646794
4     2741 days 01:19:41.646794
                 ...
995   2831 days 01:19:41.646794
996   2772 days 01:19:41.646794
997   2620 days 01:19:41.646794
998   2685 days 01:19:41.646794
999   2459 days 01:19:41.646794
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
(today - date['date']).dt.days

0      2403
1      2885
2      2816
3      2518
4      2741
       ...
995    2831
996    2772
997    2620
998    2685
999    2459
Name: date, Length: 1000, dtype: int64

In [25]:
# Months passed
date['months_passed'] = (
    (today.year - date['date'].dt.year) * 12
    + (today.month - date['date'].dt.month)
)

date['months_passed']

0      79
1      95
2      93
3      83
4      90
       ..
995    93
996    91
997    86
998    88
999    81
Name: months_passed, Length: 1000, dtype: int32

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [27]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [29]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# Extract Time part

In [30]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# Time difference

In [31]:
today - time['date']

0     4589 days 00:29:41.646794
1     4453 days 01:39:41.646794
2     4939 days 00:58:41.646794
3     4241 days 00:48:41.646794
4     4638 days 02:08:41.646794
                 ...
995   5228 days 00:29:41.646794
996   4549 days 02:05:41.646794
997   5014 days 01:42:41.646794
998   5130 days 01:45:41.646794
999   4402 days 01:54:41.646794
Name: date, Length: 1000, dtype: timedelta64[ns]

In [32]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.964914e+08
1      3.847452e+08
2      4.267331e+08
3      3.664253e+08
4      4.007309e+08
           ...
995    4.517010e+08
996    3.930411e+08
997    4.332158e+08
998    4.432383e+08
999    3.803397e+08
Name: date, Length: 1000, dtype: float64

In [33]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.608190e+06
1      6.412420e+06
2      7.112219e+06
3      6.107089e+06
4      6.678849e+06
           ...
995    7.528350e+06
996    6.550686e+06
997    7.220263e+06
998    7.387306e+06
999    6.338995e+06
Name: date, Length: 1000, dtype: float64

In [34]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      110136.494902
1      106873.661569
2      118536.978235
3      101784.811569
4      111314.144902
           ...
995    125472.494902
996    109178.094902
997    120337.711569
998    123121.761569
999    105649.911569
Name: date, Length: 1000, dtype: float64